
#ifndef LPC_PIN_H
#define LPC_PIN_H

#include "device.h"

#include <core/types.h>

struct pin_function {
	int function;
	int device;
	char *name;
};

enum {
	PIN_FUNCTION_AD0_1 = 0,
	PIN_FUNCTION_AD0_2,
	PIN_FUNCTION_AD0_3,
	PIN_FUNCTION_AD0_4,
	PIN_FUNCTION_AD0_6,
	PIN_FUNCTION_AD0_7,
	PIN_FUNCTION_AD1_0,
	PIN_FUNCTION_AD1_1,
	PIN_FUNCTION_AD1_2,
	PIN_FUNCTION_AD1_3,
	PIN_FUNCTION_AD1_4,
	PIN_FUNCTION_AD1_5,
	PIN_FUNCTION_AD1_6,
	PIN_FUNCTION_AD1_7,
	PIN_FUNCTION_DA_AOUT,
	PIN_FUNCTION_EINT0,
	PIN_FUNCTION_EINT1,
	PIN_FUNCTION_EINT2,
	PIN_FUNCTION_EINT3,
	PIN_FUNCTION_GPIO0,
	PIN_FUNCTION_GPIO1,
	PIN_FUNCTION_GPIO2,
	PIN_FUNCTION_GPIO3,
	PIN_FUNCTION_GPIO4,
	PIN_FUNCTION_GPIO5,
	PIN_FUNCTION_GPIO6,
	PIN_FUNCTION_GPIO7,
	PIN_FUNCTION_GPIO8,
	PIN_FUNCTION_GPIO9,
	PIN_FUNCTION_GPIO10,
	PIN_FUNCTION_GPIO11,
	PIN_FUNCTION_GPIO12,
	PIN_FUNCTION_GPIO13,
	PIN_FUNCTION_GPIO14,
	PIN_FUNCTION_GPIO15,
	PIN_FUNCTION_GPIO16,
	PIN_FUNCTION_GPIO17,
	PIN_FUNCTION_GPIO18,
	PIN_FUNCTION_GPIO19,
	PIN_FUNCTION_GPIO20,
	PIN_FUNCTION_GPIO21,
	PIN_FUNCTION_GPIO22,
	PIN_FUNCTION_GPIO23,
	PIN_FUNCTION_GPIO25,
	PIN_FUNCTION_GPIO28,
	PIN_FUNCTION_GPIO29,
	PIN_FUNCTION_GPIO30,
	PIN_FUNCTION_GPIO31,
	PIN_FUNCTION_I2C0_SCL,
	PIN_FUNCTION_I2C0_SDA,
	PIN_FUNCTION_I2C1_SCL,
	PIN_FUNCTION_I2C1_SDA,
	PIN_FUNCTION_PWM1,
	PIN_FUNCTION_PWM2,
	PIN_FUNCTION_PWM3,
	PIN_FUNCTION_PWM4,
	PIN_FUNCTION_PWM5,
	PIN_FUNCTION_PWM6,
	PIN_FUNCTION_SPI_MISO,
	PIN_FUNCTION_SPI_MOSI,
	PIN_FUNCTION_SPI_SCK,
	PIN_FUNCTION_SPI_SSEL,
	PIN_FUNCTION_SSP_MISO,
	PIN_FUNCTION_SSP_MOSI,
	PIN_FUNCTION_SSP_SCK,
	PIN_FUNCTION_SSP_SSEL,
	PIN_FUNCTION_TIMER0_C0,
	PIN_FUNCTION_TIMER0_C1,
	PIN_FUNCTION_TIMER0_C2,
	PIN_FUNCTION_TIMER0_C3,
	PIN_FUNCTION_TIMER0_M0,
	PIN_FUNCTION_TIMER0_M1,
	PIN_FUNCTION_TIMER0_M2,
	PIN_FUNCTION_TIMER0_M3,
	PIN_FUNCTION_TIMER1_C0,
	PIN_FUNCTION_TIMER1_C1,
	PIN_FUNCTION_TIMER1_C2,
	PIN_FUNCTION_TIMER1_C3,
	PIN_FUNCTION_TIMER1_M0,
	PIN_FUNCTION_TIMER1_M1,
	PIN_FUNCTION_TIMER1_M2,
	PIN_FUNCTION_TIMER1_M3,
	PIN_FUNCTION_UART0_RXD,
	PIN_FUNCTION_UART0_TXD,
	PIN_FUNCTION_UART1_CTS,
	PIN_FUNCTION_UART1_DCD,
	PIN_FUNCTION_UART1_DSR,
	PIN_FUNCTION_UART1_DTR,
	PIN_FUNCTION_UART1_RI,
	PIN_FUNCTION_UART1_RTS,
	PIN_FUNCTION_UART1_RXD,
	PIN_FUNCTION_UART1_TXD,
	PIN_FUNCTION_USB_CONNECT,
	PIN_FUNCTION_USB_UPLED,
	PIN_FUNCTION_USB_VBUS,

	NUM_PIN_FUNCTION,

	PIN_FUNCTION_NONE = -1,
};


#define PIN_NUM_FUNCTIONS (4)

struct pin {
	char *name;
	struct pin_function functions[PIN_NUM_FUNCTIONS];
};

enum {
	PIN0 = 0,
	PIN1,
	PIN2,
	PIN3,
	PIN4,
	PIN5,
	PIN6,
	PIN7,
	PIN8,
	PIN9,
	PIN10,
	PIN11,
	PIN12,
	PIN13,
	PIN14,
	PIN15,
	PIN16,
	PIN17,
	PIN18,
	PIN19,
	PIN20,
	PIN21,
	PIN22,
	PIN23,
	PIN24,
	PIN25,
	PIN26,
	PIN27,
	PIN28,
	PIN29,
	PIN30,
	PIN31,

	NUM_PIN,

	PIN_NONE = -1,
};

extern const struct pin pins[];

#endif /* !LPC_PIN_H */
