
#ifndef LPC_PIN_H
#define LPC_PIN_H

#include "device.h"

#include <core/types.h>

struct pin_function {
	int function;
	int device;
	char *name;
};

enum {
	PIN_FUNCTION_AD0_1 = 0,
	PIN_FUNCTION_AD0_2,
	PIN_FUNCTION_AD0_3,
	PIN_FUNCTION_AD0_4,
	PIN_FUNCTION_AD0_6,
	PIN_FUNCTION_AD0_7,
	PIN_FUNCTION_AD1_0,
	PIN_FUNCTION_AD1_1,
	PIN_FUNCTION_AD1_2,
	PIN_FUNCTION_AD1_3,
	PIN_FUNCTION_AD1_4,
	PIN_FUNCTION_AD1_5,
	PIN_FUNCTION_AD1_6,
	PIN_FUNCTION_AD1_7,
	PIN_FUNCTION_AOUT,
	PIN_FUNCTION_CONNECT,
	PIN_FUNCTION_EINT_0,
	PIN_FUNCTION_EINT_1,
	PIN_FUNCTION_EINT_2,
	PIN_FUNCTION_EINT_3,
	PIN_FUNCTION_GPIO_0,
	PIN_FUNCTION_GPIO_1,
	PIN_FUNCTION_GPIO_2,
	PIN_FUNCTION_GPIO_3,
	PIN_FUNCTION_GPIO_4,
	PIN_FUNCTION_GPIO_5,
	PIN_FUNCTION_GPIO_6,
	PIN_FUNCTION_GPIO_7,
	PIN_FUNCTION_GPIO_8,
	PIN_FUNCTION_GPIO_9,
	PIN_FUNCTION_GPIO_10,
	PIN_FUNCTION_GPIO_11,
	PIN_FUNCTION_GPIO_12,
	PIN_FUNCTION_GPIO_13,
	PIN_FUNCTION_GPIO_14,
	PIN_FUNCTION_GPIO_15,
	PIN_FUNCTION_GPIO_16,
	PIN_FUNCTION_GPIO_17,
	PIN_FUNCTION_GPIO_18,
	PIN_FUNCTION_GPIO_19,
	PIN_FUNCTION_GPIO_20,
	PIN_FUNCTION_GPIO_21,
	PIN_FUNCTION_GPIO_22,
	PIN_FUNCTION_GPIO_23,
	PIN_FUNCTION_GPIO_25,
	PIN_FUNCTION_GPIO_28,
	PIN_FUNCTION_GPIO_29,
	PIN_FUNCTION_GPIO_30,
	PIN_FUNCTION_GPIO_31,
	PIN_FUNCTION_I2C0_SCL,
	PIN_FUNCTION_I2C0_SDA,
	PIN_FUNCTION_I2C1_SCL,
	PIN_FUNCTION_I2C1_SDA,
	PIN_FUNCTION_PWM_1,
	PIN_FUNCTION_PWM_2,
	PIN_FUNCTION_PWM_3,
	PIN_FUNCTION_PWM_4,
	PIN_FUNCTION_PWM_5,
	PIN_FUNCTION_PWM_6,
	PIN_FUNCTION_SPI_MISO,
	PIN_FUNCTION_SPI_MOSI,
	PIN_FUNCTION_SPI_SCK,
	PIN_FUNCTION_SPI_SSEL,
	PIN_FUNCTION_SSP_MISO,
	PIN_FUNCTION_SSP_MOSI,
	PIN_FUNCTION_SSP_SCK,
	PIN_FUNCTION_SSP_SSEL,
	PIN_FUNCTION_TIMER0_C0,
	PIN_FUNCTION_TIMER0_C1,
	PIN_FUNCTION_TIMER0_C2,
	PIN_FUNCTION_TIMER0_C3,
	PIN_FUNCTION_TIMER0_M0,
	PIN_FUNCTION_TIMER0_M1,
	PIN_FUNCTION_TIMER0_M2,
	PIN_FUNCTION_TIMER0_M3,
	PIN_FUNCTION_TIMER1_C0,
	PIN_FUNCTION_TIMER1_C1,
	PIN_FUNCTION_TIMER1_C2,
	PIN_FUNCTION_TIMER1_C3,
	PIN_FUNCTION_TIMER1_M0,
	PIN_FUNCTION_TIMER1_M1,
	PIN_FUNCTION_TIMER1_M2,
	PIN_FUNCTION_TIMER1_M3,
	PIN_FUNCTION_UART0_RXD,
	PIN_FUNCTION_UART0_TXD,
	PIN_FUNCTION_UART1_CTS,
	PIN_FUNCTION_UART1_DCD,
	PIN_FUNCTION_UART1_DSR,
	PIN_FUNCTION_UART1_DTR,
	PIN_FUNCTION_UART1_RI,
	PIN_FUNCTION_UART1_RTS,
	PIN_FUNCTION_UART1_RXD,
	PIN_FUNCTION_UART1_TXD,
	PIN_FUNCTION_UPLED,
	PIN_FUNCTION_VBUS,

	NUM_PIN_FUNCTION,

	PIN_FUNCTION_NONE = -1,
};


#define PIN_NUM_FUNCTIONS (4)

struct pin {
	char *name;
	struct pin_function functions[PIN_NUM_FUNCTIONS];
};

enum {
	PIN_0 = 0,
	PIN_1,
	PIN_2,
	PIN_3,
	PIN_4,
	PIN_5,
	PIN_6,
	PIN_7,
	PIN_8,
	PIN_9,
	PIN_10,
	PIN_11,
	PIN_12,
	PIN_13,
	PIN_14,
	PIN_15,
	PIN_16,
	PIN_17,
	PIN_18,
	PIN_19,
	PIN_20,
	PIN_21,
	PIN_22,
	PIN_23,
	PIN_24,
	PIN_25,
	PIN_26,
	PIN_27,
	PIN_28,
	PIN_29,
	PIN_30,
	PIN_31,

	NUM_PIN,

	PIN_NONE = -1,
};

extern const struct pin pins[];

#endif /* !LPC_PIN_H */
